//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Planning.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnuSuchi3
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnuSuchi3()
        {
            this.AnuSuchi3_Bhuktani = new HashSet<AnuSuchi3_Bhuktani>();
            this.AnuSuchi3_Expenses = new HashSet<AnuSuchi3_Expenses>();
            this.AnuSuchi3_Income = new HashSet<AnuSuchi3_Income>();
            this.AnuSuchi3_Maujat = new HashSet<AnuSuchi3_Maujat>();
            this.AnuSuchi3_Project_Work_Detail = new HashSet<AnuSuchi3_Project_Work_Detail>();
            this.AnuSuchi3_Work_Division = new HashSet<AnuSuchi3_Work_Division>();
        }
    
        public int AnuSuchi3_Id { get; set; }
        public Nullable<int> Planing_Samjhauta_Id { get; set; }
        public string Project_Name { get; set; }
        public string Project_Place { get; set; }
        public string Estimated_Amount { get; set; }
        public string Project_Start_Date { get; set; }
        public string Project_End_Date { get; set; }
        public string Upabhokta_Samiti_Name { get; set; }
        public string Adakshya_Name { get; set; }
        public string Total_Members { get; set; }
        public string Male_No { get; set; }
        public string Female_No { get; set; }
        public string Total_Benificial_No { get; set; }
        public string Rohabar_Name { get; set; }
        public string Rohabar_Position { get; set; }
        public Nullable<System.DateTime> Rohabar_Date { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnuSuchi3_Bhuktani> AnuSuchi3_Bhuktani { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnuSuchi3_Expenses> AnuSuchi3_Expenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnuSuchi3_Income> AnuSuchi3_Income { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnuSuchi3_Maujat> AnuSuchi3_Maujat { get; set; }
        public virtual Planning_Samjhauta Planning_Samjhauta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnuSuchi3_Project_Work_Detail> AnuSuchi3_Project_Work_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnuSuchi3_Work_Division> AnuSuchi3_Work_Division { get; set; }
    }
}
