//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Planning.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anusuchi6_Janasahabhagita
    {
        public int Anusuchi6_Janasahabhagita_Id { get; set; }
        public Nullable<int> Anusuchi6_Id { get; set; }
        public string Janasahabhagita_Amount { get; set; }
        public string Sharam_Amount { get; set; }
        public string Jinsi_Amount { get; set; }
        public string Technical_Review_Amount { get; set; }
        public string Upabhikta_Decision_Amount { get; set; }
        public string Kista_Rakam_Demand { get; set; }
        public string Field_Supervise_Decision { get; set; }
        public string Main_Expenses { get; set; }
    
        public virtual Anusuchi6 Anusuchi6 { get; set; }
    }
}
