//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Planning.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anusuchi4_Income
    {
        public int Anusuchi4_Income_Id { get; set; }
        public Nullable<int> Anusuchi4_Id { get; set; }
        public string First_Kista { get; set; }
        public string Second_Kista { get; set; }
        public string Third_Kista { get; set; }
        public string Janashram { get; set; }
        public string Bastugat_Sahayata { get; set; }
        public string Lagat_Sahabhagita { get; set; }
    
        public virtual AnuSuchi4 AnuSuchi4 { get; set; }
    }
}
