//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Planning.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnuSuchi7
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnuSuchi7()
        {
            this.AnuSuchi7_Anugaman_Samiti = new HashSet<AnuSuchi7_Anugaman_Samiti>();
            this.AnuSuchi7_Upabhokta_Samiti = new HashSet<AnuSuchi7_Upabhokta_Samiti>();
        }
    
        public int AnuSuchi7_Id { get; set; }
        public Nullable<int> Planning_Samjhauta_Id { get; set; }
        public Nullable<System.DateTime> Samiti_Estd_Date { get; set; }
        public string Samiti_Address { get; set; }
        public string Established_Type { get; set; }
        public string Adakshyata { get; set; }
        public string Total_Present_No { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnuSuchi7_Anugaman_Samiti> AnuSuchi7_Anugaman_Samiti { get; set; }
        public virtual Planning_Samjhauta Planning_Samjhauta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnuSuchi7_Upabhokta_Samiti> AnuSuchi7_Upabhokta_Samiti { get; set; }
    }
}
