//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Planning.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnuSuchi4
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnuSuchi4()
        {
            this.Anusuchi4_Expenses = new HashSet<Anusuchi4_Expenses>();
            this.Anusuchi4_Income = new HashSet<Anusuchi4_Income>();
        }
    
        public int AnuSuchi4_Id { get; set; }
        public Nullable<int> Planning_Samjhauta_Id { get; set; }
        public string Project_Name { get; set; }
        public string Project_Place { get; set; }
        public string Project_Estimated_Amount { get; set; }
        public string Fiscal_Year { get; set; }
        public string Project_Approval_Date { get; set; }
        public string Project_To_Finish_Date { get; set; }
        public string Project_Ended_Date { get; set; }
        public Nullable<System.DateTime> Samiti_Expenses_Approval_Date { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anusuchi4_Expenses> Anusuchi4_Expenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anusuchi4_Income> Anusuchi4_Income { get; set; }
        public virtual Planning_Samjhauta Planning_Samjhauta { get; set; }
    }
}
