//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Planning.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnuSuchi9
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnuSuchi9()
        {
            this.AnuSuchi9_Discussion_Conclusions = new HashSet<AnuSuchi9_Discussion_Conclusions>();
            this.AnuSuchi9_Discussion_Subjects = new HashSet<AnuSuchi9_Discussion_Subjects>();
            this.AnuSuchi9_Meeting = new HashSet<AnuSuchi9_Meeting>();
            this.AnuSuchi9_Members = new HashSet<AnuSuchi9_Members>();
        }
    
        public int AnuSuchi9_Id { get; set; }
        public Nullable<int> Planning_Samjhauta_Id { get; set; }
        public string Adakshya { get; set; }
        public string Adakshya_Address { get; set; }
        public string Sachib { get; set; }
        public string Sachib_Address { get; set; }
        public string Koshadakshya { get; set; }
        public string Koshadakshya_Address { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnuSuchi9_Discussion_Conclusions> AnuSuchi9_Discussion_Conclusions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnuSuchi9_Discussion_Subjects> AnuSuchi9_Discussion_Subjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnuSuchi9_Meeting> AnuSuchi9_Meeting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnuSuchi9_Members> AnuSuchi9_Members { get; set; }
        public virtual Planning_Samjhauta Planning_Samjhauta { get; set; }
    }
}
