//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Planning.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anusuchi4_Expenses
    {
        public int Anusuchi4_Expenses_Id { get; set; }
        public Nullable<int> Anusuchi4_Id { get; set; }
        public string Jyalla { get; set; }
        public string Nirman_Samagri_Kharid { get; set; }
        public string Dhuwani { get; set; }
        public string Bhada { get; set; }
        public string Bawestapan_Kharcha { get; set; }
    
        public virtual AnuSuchi4 AnuSuchi4 { get; set; }
    }
}
