//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Planning.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anusuchi6_Solutions
    {
        public int Anusuchi6_Solutions_Id { get; set; }
        public Nullable<int> Anusuchi6_Id { get; set; }
        public string Solutions { get; set; }
    
        public virtual Anusuchi6 Anusuchi6 { get; set; }
    }
}
