//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Planning.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BhukataniItem
    {
        public int bhukataniItemId { get; set; }
        public Nullable<int> BhutaniID { get; set; }
        public Nullable<int> itemid { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public Nullable<int> deletedby { get; set; }
        public Nullable<int> updatedeby { get; set; }
        public Nullable<int> updatedby { get; set; }
    }
}
