//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Planning.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_A_Bank_List
    {
        public int Class_A_Bank_List_Id { get; set; }
        public string Bank_Name_Nepali { get; set; }
        public string Bank_Name_English { get; set; }
    }
}
