//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Planning.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Darkhasta_Form
    {
        public int Darkhasta_Form_Id { get; set; }
        public string Yojana_name { get; set; }
        public string Bank_Name { get; set; }
        public Nullable<int> Ward_No { get; set; }
        public string Samiti_Name { get; set; }
        public string Adakshya_Name { get; set; }
        public string Koshadakshya_Name { get; set; }
        public string Sachib_Name { get; set; }
        public string Chalani_Number { get; set; }
        public string Other_Bank_Name { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string Fiscal_Year_Record { get; set; }
    }
}
