//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Planning.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planning_Bhuktani
    {
        public int Planning_Bhuktani_Id { get; set; }
        public string Fiscal_Year_Record { get; set; }
        public string Budget_Title { get; set; }
        public string Budget_Title_Number { get; set; }
        public string Nirman_Upabhokta { get; set; }
        public string Aayojana_Karyakram { get; set; }
        public string Kul_La_Ie { get; set; }
        public string NaPa_Binayajit { get; set; }
        public string Otheers { get; set; }
        public string Jana_Sahabagita { get; set; }
        public string Peski { get; set; }
        public string Technical_Amount { get; set; }
        public string Kantigenci { get; set; }
        public string Remaining_Bhuktani_Amount { get; set; }
        public string Agrim_Shulka { get; set; }
        public string Bahal_Kar { get; set; }
        public string MarmatShmar { get; set; }
        public string Katti_Rakam { get; set; }
        public string Aanya_Raaya { get; set; }
        public string AdakshyaName { get; set; }
        public string SamjhautaDate { get; set; }
        public string Farchot_Amount { get; set; }
        public string Running_Bhuktani { get; set; }
        public string Samajik_Surekchya { get; set; }
        public string Parishramik { get; set; }
        public Nullable<int> Planning_Samjhauta_Id { get; set; }
        public Nullable<int> Bhuktani_Type { get; set; }
        public Nullable<bool> IsBhuktaniApproval { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
