//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Planning.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planning_Entry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Planning_Entry()
        {
            this.Anugamen = new HashSet<Anugaman>();
            this.Planning_Entry_Anudan = new HashSet<Planning_Entry_Anudan>();
            this.Planning_Entry_Kista_Detail = new HashSet<Planning_Entry_Kista_Detail>();
        }
    
        public int Planning_Entry_Id { get; set; }
        public Nullable<int> Planning_Samjhauta_Id { get; set; }
        public string FiscalYear { get; set; }
        public string Planning_Name { get; set; }
        public string Planning_Start_Date { get; set; }
        public string Planning_End_Date { get; set; }
        public string Work_Details { get; set; }
        public string Amount_Estimate { get; set; }
        public Nullable<int> Work_Type { get; set; }
        public Nullable<int> Ward_No { get; set; }
        public Nullable<int> Work_Area { get; set; }
        public string SerialNo { get; set; }
        public Nullable<int> Budget_Source { get; set; }
        public string Planning_Type { get; set; }
        public string UpaBhoktaSamiti_HeadName { get; set; }
        public string Contractor_Name { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anugaman> Anugamen { get; set; }
        public virtual Budget_Source Budget_Source1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Planning_Entry_Anudan> Planning_Entry_Anudan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Planning_Entry_Kista_Detail> Planning_Entry_Kista_Detail { get; set; }
        public virtual Planning_Samjhauta Planning_Samjhauta { get; set; }
        public virtual Work_Area Work_Area1 { get; set; }
        public virtual Work_Type Work_Type1 { get; set; }
    }
}
