//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Planning.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PLANNING_OCT_03Entities : DbContext
    {
        public PLANNING_OCT_03Entities()
            : base("name=PLANNING_OCT_03Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Aayojana_Maintainance> Aayojana_Maintainance { get; set; }
        public virtual DbSet<Amanat_Deatils> Amanat_Deatils { get; set; }
        public virtual DbSet<Anugaman> Anugamen { get; set; }
        public virtual DbSet<AnuSuchi1> AnuSuchi1 { get; set; }
        public virtual DbSet<AnuSuchi10> AnuSuchi10 { get; set; }
        public virtual DbSet<AnuSuchi10_Discussion_Conclusions> AnuSuchi10_Discussion_Conclusions { get; set; }
        public virtual DbSet<AnuSuchi10_Discussion_Subjects> AnuSuchi10_Discussion_Subjects { get; set; }
        public virtual DbSet<AnuSuchi10_Meeting> AnuSuchi10_Meeting { get; set; }
        public virtual DbSet<AnuSuchi10_Members> AnuSuchi10_Members { get; set; }
        public virtual DbSet<AnuSuchi11> AnuSuchi11 { get; set; }
        public virtual DbSet<AnuSuchi3_Bhuktani> AnuSuchi3_Bhuktani { get; set; }
        public virtual DbSet<AnuSuchi3_Expenses> AnuSuchi3_Expenses { get; set; }
        public virtual DbSet<AnuSuchi3_Income> AnuSuchi3_Income { get; set; }
        public virtual DbSet<AnuSuchi3_Maujat> AnuSuchi3_Maujat { get; set; }
        public virtual DbSet<AnuSuchi3_Project_Work_Detail> AnuSuchi3_Project_Work_Detail { get; set; }
        public virtual DbSet<AnuSuchi3_Work_Division> AnuSuchi3_Work_Division { get; set; }
        public virtual DbSet<Anusuchi4_Expenses> Anusuchi4_Expenses { get; set; }
        public virtual DbSet<Anusuchi4_Income> Anusuchi4_Income { get; set; }
        public virtual DbSet<Anusuchi6> Anusuchi6 { get; set; }
        public virtual DbSet<Anusuchi6_Janasahabhagita> Anusuchi6_Janasahabhagita { get; set; }
        public virtual DbSet<Anusuchi6_Karyalaya> Anusuchi6_Karyalaya { get; set; }
        public virtual DbSet<Anusuchi6_Solutions> Anusuchi6_Solutions { get; set; }
        public virtual DbSet<AnuSuchi7> AnuSuchi7 { get; set; }
        public virtual DbSet<AnuSuchi7_Anugaman_Samiti> AnuSuchi7_Anugaman_Samiti { get; set; }
        public virtual DbSet<AnuSuchi7_Upabhokta_Samiti> AnuSuchi7_Upabhokta_Samiti { get; set; }
        public virtual DbSet<AnuSuchi9> AnuSuchi9 { get; set; }
        public virtual DbSet<AnuSuchi9_Discussion_Conclusions> AnuSuchi9_Discussion_Conclusions { get; set; }
        public virtual DbSet<AnuSuchi9_Discussion_Subjects> AnuSuchi9_Discussion_Subjects { get; set; }
        public virtual DbSet<AnuSuchi9_Meeting> AnuSuchi9_Meeting { get; set; }
        public virtual DbSet<AnuSuchi9_Members> AnuSuchi9_Members { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Beneficiaries_Group> Beneficiaries_Group { get; set; }
        public virtual DbSet<BhukataniItem> BhukataniItems { get; set; }
        public virtual DbSet<Budget_Source> Budget_Source { get; set; }
        public virtual DbSet<Class_A_Bank_List> Class_A_Bank_List { get; set; }
        public virtual DbSet<DateConversion_TblNepaliCalender> DateConversion_TblNepaliCalender { get; set; }
        public virtual DbSet<Fiscal_Year_Record> Fiscal_Year_Record { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Kar_Katti> Kar_Katti { get; set; }
        public virtual DbSet<Organization_Representative> Organization_Representative { get; set; }
        public virtual DbSet<Organization_Setup> Organization_Setup { get; set; }
        public virtual DbSet<Payment_Records> Payment_Records { get; set; }
        public virtual DbSet<Planning_Documents> Planning_Documents { get; set; }
        public virtual DbSet<Planning_Entry_Anudan> Planning_Entry_Anudan { get; set; }
        public virtual DbSet<Planning_Entry_Kista_Detail> Planning_Entry_Kista_Detail { get; set; }
        public virtual DbSet<Planning_Samjhauta> Planning_Samjhauta { get; set; }
        public virtual DbSet<Project_Other_Source> Project_Other_Source { get; set; }
        public virtual DbSet<Project_Source_Detail> Project_Source_Detail { get; set; }
        public virtual DbSet<Samiti_Detail> Samiti_Detail { get; set; }
        public virtual DbSet<Sarta_Setup> Sarta_Setup { get; set; }
        public virtual DbSet<UpaBhokta_Samiti_Members_Details> UpaBhokta_Samiti_Members_Details { get; set; }
        public virtual DbSet<UpbhoktaSamiti_Details> UpbhoktaSamiti_Details { get; set; }
        public virtual DbSet<Upload_File> Upload_File { get; set; }
        public virtual DbSet<Work_Area> Work_Area { get; set; }
        public virtual DbSet<Work_Type> Work_Type { get; set; }
        public virtual DbSet<Planning_Bhuktani> Planning_Bhuktani { get; set; }
        public virtual DbSet<Planning_Entry> Planning_Entry { get; set; }
        public virtual DbSet<Project_Entry_Detail> Project_Entry_Detail { get; set; }
        public virtual DbSet<AnuSuchi4> AnuSuchi4 { get; set; }
        public virtual DbSet<AnuSuchi3> AnuSuchi3 { get; set; }
        public virtual DbSet<AnuSuchi5> AnuSuchi5 { get; set; }
        public virtual DbSet<Darkhasta_Form> Darkhasta_Form { get; set; }
        public virtual DbSet<Municipality_Samiti_Manjuri_Patra> Municipality_Samiti_Manjuri_Patra { get; set; }
    
        public virtual ObjectResult<Nullable<int>> IsNepaliDateExist(string year, string month)
        {
            var yearParameter = year != null ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(string));
    
            var monthParameter = month != null ?
                new ObjectParameter("month", month) :
                new ObjectParameter("month", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("IsNepaliDateExist", yearParameter, monthParameter);
        }
    
        public virtual ObjectResult<string> sp_GetLocalDate(Nullable<System.DateTime> romanDate, Nullable<int> format)
        {
            var romanDateParameter = romanDate.HasValue ?
                new ObjectParameter("RomanDate", romanDate) :
                new ObjectParameter("RomanDate", typeof(System.DateTime));
    
            var formatParameter = format.HasValue ?
                new ObjectParameter("Format", format) :
                new ObjectParameter("Format", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_GetLocalDate", romanDateParameter, formatParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> sp_GetRomanDate(Nullable<int> localYear, Nullable<int> localMonth, Nullable<int> localDay)
        {
            var localYearParameter = localYear.HasValue ?
                new ObjectParameter("LocalYear", localYear) :
                new ObjectParameter("LocalYear", typeof(int));
    
            var localMonthParameter = localMonth.HasValue ?
                new ObjectParameter("LocalMonth", localMonth) :
                new ObjectParameter("LocalMonth", typeof(int));
    
            var localDayParameter = localDay.HasValue ?
                new ObjectParameter("LocalDay", localDay) :
                new ObjectParameter("LocalDay", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("sp_GetRomanDate", localYearParameter, localMonthParameter, localDayParameter);
        }
    }
}
