//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Planning.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planning_Documents
    {
        public int Planning_Documents_Id { get; set; }
        public Nullable<int> Planning_Samjhauta_Id { get; set; }
        public string Fiscal_Year { get; set; }
        public string Project_Name { get; set; }
        public string Upabhokta_Gathan { get; set; }
        public string Nirnaya { get; set; }
        public string Samjhauta { get; set; }
        public string Anuman { get; set; }
        public string Mapan { get; set; }
        public string Pramanikaran { get; set; }
        public string Karya_Sampanna { get; set; }
        public string Bhuktani_Nibedan { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual Planning_Samjhauta Planning_Samjhauta { get; set; }
    }
}
