//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning.Planning.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Samiti_Detail
    {
        public int Samiti_Detail_Id { get; set; }
        public Nullable<int> Planning_Samjhauta_Id { get; set; }
        public Nullable<System.DateTime> Samiti_Estd_Date { get; set; }
        public string Adakshya { get; set; }
        public string AdakshyaContactNumber { get; set; }
        public string SachibContactNumber { get; set; }
        public string KoshadakshyaConctactNumber { get; set; }
        public string SachibContractNumber { get; set; }
        public string Sachib { get; set; }
        public string Koshadakshya { get; set; }
        public string Sadashya { get; set; }
        public string Beneficiaries_Attendance { get; set; }
        public string Beneficiaries_Absent { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual Planning_Samjhauta Planning_Samjhauta { get; set; }
    }
}
